name: Ansible + Terraform
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ansible-playbook site.yaml
